### ISSUE TITLE
能否打个3.0的包

### ISSUE THREAD

**Issue by 0xddy** [ttqftech/FFBox#35]
yarn 运行不起来 

`E:\FFBox-3.0>yarn electron:serve
yarn run v1.22.17
$ vue-cli-service electron:serve
E:\FFBox-3.0\node_modules\electron\index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (E:\FFBox-3.0\node_modules\electron\index.js:14:11)
    at Object.<anonymous> (E:\FFBox-3.0\node_modules\electron\index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\FFBox-3.0\node_modules\vue-cli-plugin-electron-builder\lib\testWithSpectron.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by ttqftech** [comment]
请根据错误提示进行操作以解决此问题。
另外，3.x 版本已不再维护，谢谢您的反馈☺️
